---
title: The Greatest Story Ever
baseURL: "/"
params:
  language: en-GB
  layout_style: horizontal
  google_analytics: UA-164034709-1
  header:
    title: The Greatest Story Ever
    sub_title: Family Bible Course
    logo_img: 
    has_nav: true
  footer:
    content: The Greatest Story Ever can be shared with other families but the content
      must not be copied in other publications, mass produced or retailed in part
      or in whole.
    links:
    - text: The Bible Course
      url: https://www.biblesociety.org.uk/explore-the-bible/the-bible-course/
      new_window: true
    copyright: "&copy; 2020 The Ollerton Family."
    supporting_content: 'For a youth/adult experience of the whole Bible: [The Bible
      Course](https://www.biblesociety.org.uk/explore-the-bible/the-bible-course/
      "The Bible Course")'
  google-analytics: UA-164034709-1
disableKinds:
- RSS
permalinks:
  posts: "/stories/:title/"
  timeline: "/timeline/:title/"
taxonomies:
  timeline: timeline
markup:
  goldmark:
    renderer:
      unsafe: true
