---
title: The Greatest Story Ever
baseURL: "/"
params:
  language: en-GB
  layout_style: grid
  palette: blue
  header:
    title: The Greatest Story Ever
    logo_img: 
    has_nav: true
  footer:
    content: "&copy; 2020 All rights reserved Andrew &amp; Charlotte Ollerton."
    links: []
    has_social: false
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
permalinks:
  posts: "/stories/:title/"
  sets: "/sets/:title/"
