---
title: The Greatest Story Ever
baseURL: "/"
language: en-GB
params:
  layout_style: grid
  palette: blue
  header:
    title: The Greatest Story Ever
    logo_img: 
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: The Bible Course
      url: https://www.biblesociety.org.uk/explore-the-bible/the-bible-course/
      new_window: true
    has_social: false
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
permalinks:
  posts: "/stories/:title/"
