---
title: Greatest Story Ever
baseURL: "/"
params:
  language: en-GB
  layout_style: horizontal
  palette: blue
  google_analytics: UA-164034709-1
  header:
    title: Greatest Story Ever
    sub_title: Family Bible Course
    logo_img: 
    has_nav: true
  footer:
    content: "&copy; 2020 All rights reserved Andrew &amp; Charlotte Ollerton."
    links: []
    has_social: false
  google-analytics: UA-164034709-1
disableKinds:
- RSS
permalinks:
  posts: "/stories/:title/"
  sets: "/sets/:title/"
taxonomies:
  set: sets
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - url: "/sets/"
    name: Sets
    weight: 2
