---
title: Greatest Story Ever
baseURL: "/"
params:
  language: en-GB
  layout_style: horizontal
  palette: blue
  google_analytics: UA-164034709-1
  header:
    title: Greatest Story Ever
    sub_title: Family Bible Course
    logo_img: 
    has_nav: true
  footer:
    content: "&copy; 2020 The Ollerton Family."
    links:
    - text: The Bible Course
      url: https://www.biblesociety.org.uk/explore-the-bible/the-bible-course/
      new_window: true
  google-analytics: UA-164034709-1
disableKinds:
- RSS
permalinks:
  posts: "/stories/:title/"
  timeline: "/timeline/:title/"
taxonomies:
  timeline: timeline
markup:
  goldmark:
    renderer:
      unsafe: true
