---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Card Content
- type: directory
  path: content/posts
  label: Stories
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/timeline
  label: Timeline
  create: documents
  match: "**/*md"
  templates:
  - set
- type: heading
  label: Site content
- type: document
  path: content/_index.md
  label: Homepage
  templates:
  - home
- type: directory
  path: content
  label: Pages
  create: documents
  match: "**/*"
  exclude: "{posts/**,timeline/**,_index.md,contact.md}"
  templates:
  - page
- type: heading
  label: Configuration
- type: document
  path: content/contact.md
  label: Contact
  templates:
  - contact
- type: document
  path: data/subscribe.json
  label: Subscribe
  templates:
  - subscribe
- type: document
  path: config.yaml
  label: Site configuration
  templates:
  - config
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
