---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Stories
  create: all
  match: "**/*"
  templates:
  - post
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{posts/**,_index.md,contact.md}"
  templates:
  - page
- type: document
  path: data/author.json
  label: Author
  templates:
  - author
- type: heading
  label: Configuration
- type: document
  path: content/contact.md
  label: Contact
  templates:
  - contact
- type: document
  path: data/subscribe.json
  label: Subscribe
  templates:
  - subscribe
- type: document
  path: data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: config.yaml
  label: Global Site Config
  templates:
  - config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.47'
